<? php
 	$ destination = "Jepang" ;
 		Ganti ( $ tujuan ) {
 			kasus  "Las Vegas" :
 		echo  "Bawakan tambahan $ 500" ;
 	istirahat ;
 			case  "Amsterdam" :
 		echo  "Bawalah pikiran terbuka" ;
 	istirahat ;
 			case  "Marocco" :
 		echo  "Bawakan 15 botol Tabir Surya SPF 50" ;
 	istirahat ;
 			kasus  "Tokyo" :
 		echo  "Bawalah banyak uang" ;
 	istirahat ;
 			case  "Kepulauan Karibia" :
 		echo  "Bawalah baju renang" ;
 	istirahat ;
 	}
?>